---
title: Birds
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: aviary.cpp
  - field: file2
    name: aviary.hpp
  - field: file3
    name: duck.hpp
  - field: file4
    name: owl.hpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_3/bird
  cmd: /entrypoint/run.py
