---
title: Vehicle register
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: aircraft.cpp
  - field: file2
    name: boat.cpp
  - field: file3
    name: register.cpp
  - field: file4
    name: vehicle.cpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_4/register/test
  cmd: /entrypoint/run.py
