---
title: Overload operators
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: geomvector.hpp
  - field: file2
    name: geomvector.cpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_3/overload_operators
  cmd: /entrypoint/run.py
