---
title: Library
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: book.hpp
  - field: file2
    name: book.cpp
  - field: file3
    name: customer.hpp
  - field: file4
    name: customer.cpp
  - field: file5
    name: library.hpp
  - field: file6
    name: library.cpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_2/library
  cmd: /entrypoint/run.py
