---
title: Mammals
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: dog.hpp
  - field: file2
    name: dog.cpp
  - field: file3
    name: cat.hpp
  - field: file4
    name: cat.cpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_3/mammals
  cmd: /entrypoint/run.py
