---
title: Trolls and dragons
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: creature.hpp
  - field: file2
    name: creature.cpp
  - field: file3
    name: troll.hpp
  - field: file4
    name: troll.cpp
  - field: file5
    name: dragon.hpp
  - field: file6
    name: dragon.cpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_3/trolls_and_dragons
  cmd: /entrypoint/run.py
