---
title: Polynomial
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: poly.cpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_4/polynomial/test
  cmd: /entrypoint/run.py
