---
title: Restricted pointer
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: restricted_ptr.hpp
  - field: file2
    name: restricted_ref_counter.hpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_4/restr_ptr/test
  cmd: /entrypoint/run.py
