---
title: Transcript
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: transcript.cpp
  - field: file2
    name: transcript.hpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_5/transcript/test
  cmd: /entrypoint/run.py
