---
title: List
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: list.cpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_2/list
  cmd: /entrypoint/run.py
