---
title: ToString
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: to_string.hpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_4/to_string/test
  cmd: /entrypoint/run.py
