---
title: Matrix rotation
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: matrix.cpp

container:
  image: lainets/grade-c:8.3-1.0-3.4u5
  mount: _exercises/Module_2/matrix
  cmd: /entrypoint/run.py
